name: "Salesforce UAT Deployment Pipeline"
run-name: "Salesforce UAT Deployment Pipeline"

on:
  workflow_dispatch: #Manual Run the pipeline
  PULL_REQUEST:
    types: 
      - closed
    paths: 
      - 'force-app/**'
    branches:
      - UAT
      - uat

env:
  ORG_DEFAULT_ALIAS: 'UAT_ORG'
  NODE_VERSION: '>=20.9.0'
  JAVA_VERSION: '>=11'
jobs:
  build-salesforce:
      name: "Build & Validate"
      uses: "./.github/workflows/template.yaml"
      with:
        environment: UAT
        runner: macos-latest
      secrets: inherit
