name: "Salesforce Development Pipeline"
run-name: "Salesforce Development Pipeline Run"

on:
  workflow_dispatch: #Manual Run the pipeline
  push:
    paths: 
      - 'force-app/**'
    branches:
      - feature/**

env:
  ORG_DEFAULT_ALIAS: 'DEV_ORG'
  NODE_VERSION: '>=20.9.0'
  JAVA_VERSION: '>=11'
jobs:
  build-salesforce:
      name: "Build & Validate"
      uses: "./.github/workflows/template.yaml"
      with:
        environment: dev
        runner: macos-latest
      secrets: inherit
