name: "Salesforce UAT Pipeline"
run-name: "Salesforce Pipeline Run"

on:
  workflow_dispatch: #Manual Run the pipeline
  pull_request:
    types:
      - opened
#      - closed
      - synchronize
    paths: 
      - 'force-app/**'
    branches:
      - UAT
      - uat

env:
  ORG_DEFAULT_ALIAS: 'UAT_ORG'
  NODE_VERSION: '>=20.9.0'
  JAVA_VERSION: '>=11'
jobs:
  build-salesforce:
      name: "Build & Validate"
      uses: "./.github/workflows/template.yaml"
      with:
        environment: UAT
        runner: macos-latest
      secrets: inherit
